# Generated by Django 4.1.2 on 2023-05-04 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Styling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('size', models.CharField(max_length=30)),
                ('silhouette', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('situation', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('tops_fit', models.CharField(max_length=100)),
                ('bottoms_fit', models.CharField(max_length=100)),
                ('bottoms_length', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
