# Generated by Django 4.1.2 on 2023-05-07 14:53

import chatgpt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0002_styling_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='styling',
            name='image',
            field=models.FileField(default=None, null=True, upload_to=chatgpt.models.upload_img),
        ),
    ]
