# Generated by Django 4.1.2 on 2023-04-18 17:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('subscription', 'subscription'), ('rental', 'rental'), ('purchase', 'purchase')], max_length=30)),
                ('amount_off', models.IntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('jpy', 'jpy')], default='jpy', max_length=3)),
                ('duration', models.CharField(choices=[('once', 'once'), ('repeting', 'repeting'), ('forever', 'forever')], max_length=30)),
                ('duration_in_month', models.IntegerField(default=None, null=True)),
                ('duration_in_times', models.IntegerField(default=1)),
                ('max_redemptions', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('percent_off', models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True)),
                ('times_redeemed', models.IntegerField(default=0)),
                ('redeem_by', models.DateField()),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issuing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('expiration', models.DateField(default=None, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{8,16}$')])),
                ('InvitationCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.invitationcode')),
            ],
        ),
    ]
