# Generated by Django 3.2 on 2022-02-28 06:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import product.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('tax', models.FloatField(blank=True, choices=[(0.1, 0.1)], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)])),
                ('review_count', models.IntegerField(blank=True, default=0, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('img', models.FileField(blank=True, default=None, null=True, upload_to=product.models.upload_product)),
                ('is_available', models.BooleanField(default=True)),
                ('is_subscription', models.CharField(choices=[('rental', 'rental'), ('basic', 'basic'), ('premium', 'premium')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(blank=True, choices=[('mens', 'メンズ'), ('ladies', 'レディース'), ('kids', 'キsッズ')], max_length=10, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='category.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='category.category')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.price')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('review', models.TextField(blank=True, max_length=500)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('on_created', models.DateTimeField(auto_now_add=True)),
                ('on_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_company', models.CharField(max_length=30)),
                ('shipping_method', models.CharField(max_length=30)),
                ('size', models.IntegerField(blank=True, choices=[(60, 60), (80, 80), (100, 100), (120, 120), (140, 140), (160, 160)])),
                ('shipping_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_choices', models.CharField(choices=[('color', 'Color'), ('condition', 'condition')], max_length=100)),
                ('variation_value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variation', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('free', 'FREE')], max_length=10)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('shoulder_width', models.IntegerField(blank=True, null=True)),
                ('chest', models.IntegerField(blank=True, null=True)),
                ('waist', models.IntegerField(blank=True, null=True)),
                ('hip', models.IntegerField(blank=True, null=True)),
                ('inseam', models.IntegerField(blank=True, null=True)),
                ('sleeve_length', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRatingGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to=product.models.upload_review_img)),
                ('on_created', models.DateTimeField(auto_now_add=True)),
                ('on_updated', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_gallery', to='product.reviewrating')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_tag', to='product.Tag'),
        ),
        migrations.AddField(
            model_name='price',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.shipping'),
        ),
        migrations.CreateModel(
            name='ImageGallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.FileField(upload_to=product.models.upload_img)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=product.models.upload_thumbnail)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product.product')),
            ],
            options={
                'verbose_name': 'image gallary',
                'verbose_name_plural': 'image gallary',
            },
        ),
    ]
