# Generated by Django 3.2 on 2022-03-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallary',
            name='thumbnail',
        ),
    ]
