# Generated by Django 3.2 on 2022-05-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_imagegallary_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(choices=[('color', 'Color'), ('condition', 'condition')], max_length=100),
        ),
    ]
