# Generated by Django 3.2 on 2022-05-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_variation_variation_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(choices=[('unused', '新品'), ('near_unused', '未使用に近い'), ('no_stain', '目立った汚れなし'), ('slightly_stain', 'やや汚れあり'), ('stain', '汚れあり')], max_length=100),
        ),
    ]
