# Generated by Django 3.2 on 2022-05-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_variation_variation_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(choices=[('新品', 'unused'), ('未使用に近い', 'near_unused'), ('目立った汚れなし', 'no_stain'), ('やや汚れあり', 'slightly_stain'), ('汚れあり', 'stain')], max_length=100),
        ),
    ]
