# Generated by Django 3.2 on 2022-05-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_variation_variation_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('S', 's'), ('M', 'm'), ('L', 'l'), ('XL', 'xl'), ('XXL', 'xxl'), ('FREE', 'free')], max_length=10),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_choices',
            field=models.CharField(choices=[('カラー', 'Color'), ('コンディション', 'condition')], max_length=100),
        ),
    ]
