# Generated by Django 3.2 on 2022-05-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20220507_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('メンズ', 'mens'), ('レディース', 'ladies'), ('キッズ', 'kids')], max_length=10, null=True),
        ),
    ]
