# Generated by Django 3.2 on 2022-05-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('メンズ', 'mens'), ('レディース', 'ladies'), ('キッズ', 'kids')], default='mens', max_length=10),
        ),
    ]
