# Generated by Django 4.1.2 on 2023-01-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20220808_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='size',
            field=models.IntegerField(blank=True, choices=[('ネコポス', 'ネコポス'), ('宅急便コンパクト', '宅急便コンパクト'), (60, 60), (80, 80), (100, 100), (120, 120), (140, 140), (160, 160)]),
        ),
    ]
