# Generated by Django 4.1.2 on 2023-01-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_description_alter_shipping_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='hem_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='rise',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('XS', 'xs'), ('S', 's'), ('M', 'm'), ('L', 'l'), ('XL', 'xl'), ('XXL', 'xxl'), ('FREE', 'free')], max_length=10),
        ),
    ]
