# Generated by Django 4.1.1 on 2023-01-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_size_hem_width_size_rise_alter_size_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='hem_width',
        ),
        migrations.RemoveField(
            model_name='size',
            name='rise',
        ),
        migrations.AddField(
            model_name='size',
            name='rize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('S', 's'), ('M', 'm'), ('L', 'l'), ('XL', 'xl'), ('XXL', 'xxl'), ('FREE', 'free')], max_length=10),
        ),
    ]
