# Generated by Django 4.1.2 on 2023-01-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_rating_alter_shipping_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='size',
            field=models.CharField(blank=True, choices=[('ネコポス', 'ネコポス'), ('宅急便コンパクト', '宅急便コンパクト'), ('0', '0'), ('60', '60'), ('80', '80'), ('100', '100'), ('120', '120'), ('140', '140'), ('160', '160')], max_length=100),
        ),
    ]
