# Generated by Django 4.1.2 on 2023-02-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_shipping_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buying_price',
            field=models.IntegerField(default=0),
        ),
    ]
