# Generated by Django 4.1.2 on 2023-02-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_buying_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallary',
            options={'verbose_name': 'イメージギャラリー', 'verbose_name_plural': 'イメージギャラリーズ'},
        ),
    ]
