# Generated by Django 4.1.1 on 2023-09-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('メンズ', 'mens'), ('レディース', 'ladies'), ('キッズ', 'kids'), ('ユニセックス', 'unisex')], default='mens', max_length=10),
        ),
    ]
