# Generated by Django 3.2 on 2022-06-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_gender'),
        ('category', '0002_remove_category_slug'),
        ('analytics', '0003_cardadditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardAddItem',
            new_name='CartAddItem',
        ),
    ]
