# Generated by Django 3.2 on 2022-05-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_remove_stripeaccount_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeaccount',
            name='plan_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
