# Generated by Django 4.1.2 on 2023-02-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0006_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_id",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
