# Generated by Django 4.1.2 on 2023-02-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0007_alter_payment_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
