# Generated by Django 4.1.2 on 2023-03-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_alter_payment_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_off', models.IntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('jpy', 'jpy')], default='jpy', max_length=3)),
                ('duration', models.CharField(choices=[('once', 'once'), ('repeting', 'repeting'), ('forever', 'forever')], max_length=30)),
                ('duration_month', models.IntegerField()),
                ('max_redemptions', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('percent_off', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('times_redeemed', models.IntegerField()),
                ('redeem_by', models.DateField()),
            ],
        ),
    ]
