# Generated by Django 4.1.2 on 2023-04-18 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0010_coupon_issuing_invitationcode_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuing',
            name='expiration',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
