# Generated by Django 3.2 on 2022-04-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_history', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResearchHistory',
        ),
    ]
