# Generated by Django 4.1.2 on 2023-02-01 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
