# Generated by Django 4.1.2 on 2023-02-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0002_remove_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'accepted'), ('Completed', 'completed'), ('Denied', 'denied'), ('Cancelled', 'cancelled')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.FloatField(choices=[(0.1, 'JP')]),
        ),
    ]
