# Generated by Django 4.1.2 on 2023-02-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0004_payment_payment_intent_id_alter_payment_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_intent_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
