# Generated by Django 4.1.2 on 2023-02-12 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0005_remove_payment_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
