# Generated by Django 4.1.2 on 2023-02-24 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0005_payment"),
        ("buying", "0006_remove_orderitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_payment",
                to="subscription.payment",
            ),
        ),
        migrations.DeleteModel(name="Payment",),
    ]
