# Generated by Django 4.1.2 on 2023-02-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buying', '0007_alter_order_payment_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_intent_id',
        ),
    ]
