# Generated by Django 3.2 on 2022-08-06 10:16

import category.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('type_name', models.CharField(max_length=30, unique=True)),
                ('image', models.FileField(upload_to=category.models.upload_type)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='category.type'),
        ),
    ]
