# Generated by Django 3.2 on 2022-08-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20220806_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'ブランド', 'verbose_name_plural': 'ブランド'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリー', 'verbose_name_plural': 'カテゴリー'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'タイプ', 'verbose_name_plural': 'タイプ'},
        ),
        migrations.RenameField(
            model_name='type',
            old_name='type_name',
            new_name='category_name',
        ),
    ]
