# Generated by Django 4.1.1 on 2023-01-11 11:20

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(upload_to=category.models.upload_category),
        ),
    ]
