# Generated by Django 4.1.2 on 2023-02-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_category_created_at_type_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
