# Generated by Django 4.1.2 on 2022-12-15 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0015_auto_20220808_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=50)),
                ('prefecture', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=50)),
                ('building_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.SmallIntegerField(choices=[(0, 'Storing'), (1, 'Leaving'), (2, 'Waste')], default=0)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='inventory.warehouse')),
            ],
        ),
    ]
