# Generated by Django 4.1.1 on 2023-01-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='country',
            field=models.CharField(default='日本', max_length=100),
        ),
    ]
