# Generated by Django 4.1.1 on 2023-09-19 01:08

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_purchase_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.FileField(default=None, null=True, upload_to=inventory.models.upload_img),
        ),
    ]
