# Generated by Django 4.1.1 on 2023-09-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='number',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
