word_list = [
    'アーペーセー', 'アクネ', 'アクネストゥディオズ', 'アーダーエラー', 'アレキサンダーマックイーン','アンブッシュ', 'アクロニウム', 'アンドゥムルメステール', 'アンリアレイジ',
    'バレンシアガ', 'バルマン', 'ベッドフォード', 'BLACK COMME des GARCONS', 'BOTTEGA VENETA', 'BOTTER', 'BURBERRY',
    'セシリーバンセン','カルバンクライン', 'コムデギャルソン', 'コムデギャルソンオム', 'コムデギャルソンオムプリュス', 'コムデギャルソンガール', 'コムデギャルソンオムドゥ', 'サカイ',  'セリーヌ', 'ケンゾー', 'シャネル', 'チャールズジェフリーラバーボーイ',
    'ダイリク', 'ディオール', 'ドルチェアンドガッバーナ', 'ダブレット', 'ドリスヴァンノッテン',
    'ファセッタズム', 'フェンディ', 'フェティコ', 'フミトガンリュー',
    'ジバンシー', 'ゲーエムベーハー', 'グッチ',
    'ヘルメス', 'ヘロンプレストン', 'ハイク',
    'ジルサンダー', 'ジョンローレンスサリバン', 'ジュンヤワタナベ',
    'キココスタディノフ', 'コシェ', 'カラー', 'カイダンエディション',
    'イザベルマラン', 'イッセイミヤケ',
    'ラッドミュージシャン', 'ルメール', 'リミフゥ', 'ロエベ', 'ルイヴィトン',
    'メゾンマルジェラ', 'マメクロゴウチ', 'マークジェイコブス', 'マリーンセル', 'マルニ', 'ミュウミュウ', 'エムエムシックス', 'エムエスジーエム',
    'ナマチェコ', 'ネヘラ', 'ナイキ', 'ニナリッチ', 'ノワールケイニノミヤ',
    'オフホワイト', 'アワーレガシー',
    'ピータードゥ', 'プラダ',
    'ラフシモンズ', 'リコール', 'リックオウエンス', 'ロク',
    'シュシュトン', 'シモーネロシャ', 'ソウシオオツキ', 'ストーンアイランド', 'シュガーヒル',
    'ターク', 'テンダーパーソン', 'ザ・ロウ', 'トーガ', 'トモコイズミ', 'ティーモダンストリートウェア',
    'ナイキ', 'バレンシアガ', 'ラッドミュージシャン', 'ヨウジヤマモト', 'ワイズ', 'ティー', 'ティーモダンストリートウェア',
    'ウェールズボナー', 'ウォルターヴァンベイレンドンク','サンダーズウ'
    'アンダーカバー', 'ヴァレンティノ', 'ヴェルサーチ', 'ヴェトモン', 'ヴィヴィアンウエストウッド',
    'ヨウジヤマモト', 'ヨウジヤマモトプリュスノアール', 'ワイプロジェクト', 'ワイズ',
    'ACNE', 'ACNE STUDIOS','ADER ERROR', 'ALEXANDER MCQUEEN', 'AMBUSH', 'ANACHRONORM', 'ANN DEMEULEMEESTER', 'ANREALAGE','APC', 'A.P.C', 
    'BALENCIAGE', 'BALMAIN', 'BED J.W. FORD', 'ブラックコムデギャルソン', 'ボッテガヴィネタ', 'バーバリー',
    'CECILIE BAHNSEN','CHANEL', 'CHARLES JEFFREY LOVERBOY','CALVIN KLEIN', 'CELINE', 'COMME des GARCONS', 'COMME des GARCONS SHIRT', 'COMME des GARCONS HOMME', 'COMME des GARCONS HOMME DEUX', 'COMME des GARCONS GIRL',
    'DAIRIKU', 'DIOR', 'DOLCE&GABBANA', 'DOUBLET', 'DRIES VAN NOTEN',
    'FACETASM', 'FENDI', 'FETICO', 'FUMITO GANRYU',
    'GIVENCHY', 'GmbH', 'GUCCI',
    'HERMES', 'HERON PRESTON', 'HYKE',
    'ISABEL MARANT', 'ISSEY MIYAKE',
    'JIL SANDER', 'JOHN LAWRENCE SULLIVAN', 'JUNYA WATANABE',
    'KIKO KOSTADINOV', 'KOCHE', 'KOLOR', 'KWAIDAN EDITIONS',
    'LAD MUSICIAN', 'LEMAIRE', 'LIMI feu', 'LOEWE', 'LOUIS VUITTON',
    'MAISON MARGIELA', 'MAME KUROGOUCHI', 'MARC JACOBS', 'MARINE SERRE', 'MARNI', 'MIU MIU', 'MM6', 'MSGM',
    'NAMACHECO', 'NEHERA', 'NIKE', 'NINA RICCI', 'NOIR KEI NINOMIYA',
    'OFF-WHITE', 'OUR LEGACY',
    'PETER DO', 'PRADA',
    'RAF SIMONS', 'RequaL', 'RICK OWENS', 'ROKH',
    'SHUSHU/TONG', 'SIMONE ROCHA', 'SOSHIOTSUKI', 'STONE ISLAND', 'SUGARHILL',
    'TAAKK', 'TENDER PERSON', 'THE ROW', 'TOGA', 'TOMOKOIZUMI', 'TTT_MSW',
    'UNDERCOVER', 'VALENTINO', 'VERSACE', 'VETMENTS', 'Vivienne Westwood',
    'WALES BONNER', 'WALTER VAN BEIRENDONCK', 'XANDER ZOU',
    'YOHJI YAMAMOTO', 'YOHJI YAMAMOTO + NOIR', 'Y/PROJECT', 'Y`s',
    'COMME des GARCONS HOMME PLUS', 'COMME des GARCONS PLAY', 'DIOR', 'KENZO', 'LAD MUSICIAN', 'NIKE', 'YOHJI YAMAMOTO', 'Y`s', 'SACAI', 'TTT_MSW',
    ]