# Generated by Django 3.2 on 2022-03-04 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_adress_phonenubmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='phoneNubmer',
            field=models.CharField(default=None, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{8, 16}$')]),
        ),
    ]
