# Generated by Django 3.2 on 2022-04-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_email_subscirbe_emailsubscribe_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='phoneNubmer',
            new_name='phoneNumber',
        ),
    ]
