# Generated by Django 4.1.2 on 2022-11-13 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_account_phone_number_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='phoneNumber',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{8,16}$')]),
        ),
    ]
