# Generated by Django 4.1.2 on 2022-12-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_randomnumber_authphonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscribe',
            name='recipient_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
