# Generated by Django 4.1.2 on 2022-12-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_emailsubscribe_recipient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscribe',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
