# Generated by Django 4.1.2 on 2023-01-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_credibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='address',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='building_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='country',
            field=models.CharField(default='Japan', max_length=250),
        ),
        migrations.AlterField(
            model_name='adress',
            name='prefecture',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
