# Generated by Django 4.1.1 on 2023-02-07 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_adress_address_alter_adress_building_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credibility',
            name='review',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(-3.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
