# Generated by Django 3.2 on 2022-02-28 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reserved_start_date', models.DateTimeField(auto_now_add=True)),
                ('reserved_end_date', models.DateTimeField(blank=True, null=True)),
                ('is_reserved', models.BooleanField(default=False)),
                ('status', models.SmallIntegerField(choices=[(0, 'Requested'), (1, 'Accepted'), (2, 'Denied'), (3, 'Borrowed'), (4, 'Shipping'), (5, 'Returned')], default=0)),
                ('plan', models.CharField(choices=[('rental', 'rental'), ('basic', 'basic'), ('premium', 'premium')], max_length=20)),
                ('ip', models.CharField(blank=True, max_length=30)),
                ('payment_method', models.CharField(blank=True, max_length=30, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('shipping_price', models.IntegerField(blank=True, null=True)),
                ('shipping_number', models.CharField(blank=True, max_length=15, null=True)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.adress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('is_canceled', models.BooleanField(default=False)),
                ('cancel_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation')),
                ('variation', models.ManyToManyField(blank=True, null=True, to='product.Variation')),
            ],
        ),
    ]
