# Generated by Django 3.2 on 2022-03-16 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationitem',
            old_name='reservation',
            new_name='reservation_product',
        ),
    ]
