# Generated by Django 3.2 on 2022-03-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_reservation_reservationitem_reservation_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationitem',
            old_name='reservation_product',
            new_name='reservation',
        ),
    ]
