# Generated by Django 3.2 on 2022-03-18 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_rename_reservation_product_reservationitem_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='return_shipping_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='shipping_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{12}$')]),
        ),
    ]
