# Generated by Django 3.2 on 2022-04-08 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservationitem_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationitem',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation'),
        ),
    ]
