# Generated by Django 4.1.1 on 2023-01-14 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_alter_reservationitem_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationitem',
            name='review',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
