# Generated by Django 4.1.2 on 2023-02-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_alter_reservationitem_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationitem',
            name='is_bought',
            field=models.BooleanField(default=False),
        ),
    ]
