# Generated by Django 4.1.2 on 2023-02-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_reservationitem_is_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='shipping_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
