# Generated by Django 4.1.2 on 2023-02-24 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0005_payment"),
        ("reservation", "0015_alter_reservation_shipping_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="reservation", name="payment_method",),
        migrations.AddField(
            model_name="reservation",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="subscription.payment",
            ),
        ),
    ]
