# Generated by Django 4.1.2 on 2023-05-15 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0017_reservation_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
