# Generated by Django 4.1.2 on 2023-05-18 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0018_alter_reservation_reserved_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved_day',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 16, 35, 8, 59580, tzinfo=datetime.timezone.utc)),
        ),
    ]
