# Generated by Django 4.1.1 on 2023-09-18 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0019_reservation_reserved_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_day',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 6, 6, 45, 79741, tzinfo=datetime.timezone.utc)),
        ),
    ]
