# Generated by Django 4.1.1 on 2023-09-19 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0020_alter_reservation_reserved_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_day',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 1, 8, 19, 658292, tzinfo=datetime.timezone.utc)),
        ),
    ]
